name: PHP Composer

on:
  push:
    branches: 
      - lonely

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Switch to project directory
        run: cd $GITHUB_WORKSPACE

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Update dependencies
        run: composer update

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Package files
        run: tar -czvf files.tar.gz .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: packaged-files
          path: files.tar.gz
