name: Update Vendor and Package

on:
  push:
    branches:
      - lonely

jobs:
  update-vendor-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.x'

      - name: Install Composer dependencies
        run: composer install --no-scripts

      - name: Update vendor directory
        run: composer update --no-scripts

      - name: Create archive
        run: zip -r cos-api.zip vendor/ !(.??*)  

      - name: Upload cos-api
        uses: actions/upload-artifact@v3.1.3
        with:
          name: cos-api
          path: cos-api.zip
            